//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DiktaMe.Core.Resources;

using System.Globalization;

/// <summary>
/// Strongly-typed resource class for looking up localized strings from CoreStrings.resx.
/// </summary>
internal static class CoreStrings
{
    private static System.Resources.ResourceManager? s_resourceManager;

    private static System.Resources.ResourceManager ResourceManager
        => s_resourceManager ??= new System.Resources.ResourceManager(
            "DiktaMe.Core.Resources.CoreStrings",
            typeof(CoreStrings).Assembly);

    private static CultureInfo? s_resourceCulture;

    /// <summary>
    /// Overrides the current thread's CurrentUICulture for all resource lookups.
    /// </summary>
    internal static CultureInfo? Culture
    {
        get => s_resourceCulture;
        set => s_resourceCulture = value;
    }

    // ── Capabilities ────────────────────────────────────────────────────────

    internal static string Capabilities_CloudStt
        => ResourceManager.GetString("Capabilities_CloudStt", s_resourceCulture) ?? "Cloud STT";

    internal static string Capabilities_LocalStt
        => ResourceManager.GetString("Capabilities_LocalStt", s_resourceCulture) ?? "Local STT";

    internal static string Capabilities_NoStt
        => ResourceManager.GetString("Capabilities_NoStt", s_resourceCulture) ?? "No STT";

    internal static string Capabilities_CloudLlm
        => ResourceManager.GetString("Capabilities_CloudLlm", s_resourceCulture) ?? "Cloud LLM";

    internal static string Capabilities_Ollama
        => ResourceManager.GetString("Capabilities_Ollama", s_resourceCulture) ?? "Ollama";

    internal static string Capabilities_NoLlm
        => ResourceManager.GetString("Capabilities_NoLlm", s_resourceCulture) ?? "No LLM";

    // ── Trial provider messages ─────────────────────────────────────────────

    internal static string Trial_SessionExpired
        => ResourceManager.GetString("Trial_SessionExpired", s_resourceCulture) ?? "Trial session expired. Please sign in again.";

    internal static string Trial_QuotaExceeded
        => ResourceManager.GetString("Trial_QuotaExceeded", s_resourceCulture) ?? "Trial quota exceeded. You've used all 15,000 free words.";
}
